<?php

namespace Proxies\__CG__\App\DataWarehouseBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DimHoras extends \App\DataWarehouseBundle\Entity\DimHoras implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'actividadId', 'horasId', 'fechainicio', 'fechatermino', 'profesionalId', 'id');
        }

        return array('__isInitialized__', 'actividadId', 'horasId', 'fechainicio', 'fechatermino', 'profesionalId', 'id');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DimHoras $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setActividadId($actividadId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActividadId', array($actividadId));

        return parent::setActividadId($actividadId);
    }

    /**
     * {@inheritDoc}
     */
    public function getActividadId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActividadId', array());

        return parent::getActividadId();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorasId($horasId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorasId', array($horasId));

        return parent::setHorasId($horasId);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorasId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorasId', array());

        return parent::getHorasId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechainicio($fechainicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechainicio', array($fechainicio));

        return parent::setFechainicio($fechainicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechainicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechainicio', array());

        return parent::getFechainicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechatermino($fechatermino)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechatermino', array($fechatermino));

        return parent::setFechatermino($fechatermino);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechatermino()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechatermino', array());

        return parent::getFechatermino();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfesionalId($profesionalId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfesionalId', array($profesionalId));

        return parent::setProfesionalId($profesionalId);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfesionalId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfesionalId', array());

        return parent::getProfesionalId();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

}
