<?php

namespace Proxies\__CG__\App\DataWarehouseBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FtAvanceProyecto extends \App\DataWarehouseBundle\Entity\FtAvanceProyecto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'fechaId', 'proyecto', 'horasAvanzadas', 'horasAsignadas', 'porcentajeavance', 'id', 'valorTotal', 'valorFecha');
        }

        return array('__isInitialized__', 'fechaId', 'proyecto', 'horasAvanzadas', 'horasAsignadas', 'porcentajeavance', 'id', 'valorTotal', 'valorFecha');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FtAvanceProyecto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setFechaId($fechaId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaId', array($fechaId));

        return parent::setFechaId($fechaId);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaId', array());

        return parent::getFechaId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProyecto($proyecto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProyecto', array($proyecto));

        return parent::setProyecto($proyecto);
    }

    /**
     * {@inheritDoc}
     */
    public function getProyecto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProyecto', array());

        return parent::getProyecto();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorasAvanzadas($horasAvanzadas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorasAvanzadas', array($horasAvanzadas));

        return parent::setHorasAvanzadas($horasAvanzadas);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorasAvanzadas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorasAvanzadas', array());

        return parent::getHorasAvanzadas();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorasAsignadas($horasAsignadas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorasAsignadas', array($horasAsignadas));

        return parent::setHorasAsignadas($horasAsignadas);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorasAsignadas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorasAsignadas', array());

        return parent::getHorasAsignadas();
    }

    /**
     * {@inheritDoc}
     */
    public function setPorcentajeavance($porcentajeavance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPorcentajeavance', array($porcentajeavance));

        return parent::setPorcentajeavance($porcentajeavance);
    }

    /**
     * {@inheritDoc}
     */
    public function getPorcentajeavance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPorcentajeavance', array());

        return parent::getPorcentajeavance();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorTotal($valorTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorTotal', array($valorTotal));

        return parent::setValorTotal($valorTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorTotal', array());

        return parent::getValorTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorFecha($valorFecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorFecha', array($valorFecha));

        return parent::setValorFecha($valorFecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorFecha', array());

        return parent::getValorFecha();
    }

}
