<?php

namespace Proxies\__CG__\App\MediBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Proyecto extends \App\MediBundle\Entity\Proyecto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'nombreProyecto', 'nombreProyecto1', 'nombreProyecto2', 'username', 'username1', 'descripcion', 'fechaInicio', 'fechaFin', 'status', 'horasProgramadas', 'horasAvanzadas', 'asignacion', 'clientes', 'factTable', 'avancesProfesionales', 'excepcionesPlazo', 'asignacionEtapa', 'hito', 'avanceHoras', 'avance', 'avanceProfesionales', 'avanceProfesionalesLittle', 'finanzas', 'licitacion');
        }

        return array('__isInitialized__', 'id', 'nombreProyecto', 'nombreProyecto1', 'nombreProyecto2', 'username', 'username1', 'descripcion', 'fechaInicio', 'fechaFin', 'status', 'horasProgramadas', 'horasAvanzadas', 'asignacion', 'clientes', 'factTable', 'avancesProfesionales', 'excepcionesPlazo', 'asignacionEtapa', 'hito', 'avanceHoras', 'avance', 'avanceProfesionales', 'avanceProfesionalesLittle', 'finanzas', 'licitacion');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Proyecto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreProyecto($nombreProyecto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreProyecto', array($nombreProyecto));

        return parent::setNombreProyecto($nombreProyecto);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsignacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsignacion', array());

        return parent::getAsignacion();
    }

    /**
     * {@inheritDoc}
     */
    public function getAsignacionEtapa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsignacionEtapa', array());

        return parent::getAsignacionEtapa();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreProyecto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreProyecto', array());

        return parent::getNombreProyecto();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreProyecto1($nombreProyecto1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreProyecto1', array($nombreProyecto1));

        return parent::setNombreProyecto1($nombreProyecto1);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreProyecto1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreProyecto1', array());

        return parent::getNombreProyecto1();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreProyecto2($nombreProyecto2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreProyecto2', array($nombreProyecto2));

        return parent::setNombreProyecto2($nombreProyecto2);
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreProyecto3($nombreProyecto3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreProyecto3', array($nombreProyecto3));

        return parent::setNombreProyecto3($nombreProyecto3);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreProyecto2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreProyecto2', array());

        return parent::getNombreProyecto2();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername1', array());

        return parent::getUsername1();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaInicio($fechaInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaInicio', array($fechaInicio));

        return parent::setFechaInicio($fechaInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaInicio', array());

        return parent::getFechaInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaFin($fechaFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaFin', array($fechaFin));

        return parent::setFechaFin($fechaFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaFin', array());

        return parent::getFechaFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorasPlanificadas($horasPlanificadas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorasPlanificadas', array($horasPlanificadas));

        return parent::setHorasPlanificadas($horasPlanificadas);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorasPlanificadas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorasPlanificadas', array());

        return parent::getHorasPlanificadas();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfesional($profesional)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfesional', array($profesional));

        return parent::setProfesional($profesional);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfesional()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfesional', array());

        return parent::getProfesional();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorasProgramadas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorasProgramadas', array());

        return parent::getHorasProgramadas();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorasProgramadas($horasProgramadas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorasProgramadas', array($horasProgramadas));

        return parent::setHorasProgramadas($horasProgramadas);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getHorasAvanzadas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorasAvanzadas', array());

        return parent::getHorasAvanzadas();
    }

    /**
     * {@inheritDoc}
     */
    public function removeHorasAvanzadas($hora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHorasAvanzadas', array($hora));

        return parent::removeHorasAvanzadas($hora);
    }

    /**
     * {@inheritDoc}
     */
    public function setHorasAvanzadas($hora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorasAvanzadas', array($hora));

        return parent::setHorasAvanzadas($hora);
    }

    /**
     * {@inheritDoc}
     */
    public function setLicitacion($licitacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLicitacion', array($licitacion));

        return parent::setLicitacion($licitacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getLicitacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLicitacion', array());

        return parent::getLicitacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinanzas($finanzas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinanzas', array($finanzas));

        return parent::setFinanzas($finanzas);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinanzas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinanzas', array());

        return parent::getFinanzas();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientes($clientes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientes', array($clientes));

        return parent::setClientes($clientes);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientes', array());

        return parent::getClientes();
    }

    /**
     * {@inheritDoc}
     */
    public function getFactTable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFactTable', array());

        return parent::getFactTable();
    }

    /**
     * {@inheritDoc}
     */
    public function setFactTable($arrayObjetos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFactTable', array($arrayObjetos));

        return parent::setFactTable($arrayObjetos);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvancesProfesionales()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvancesProfesionales', array());

        return parent::getAvancesProfesionales();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvancesProfesionales($avancesProfesionales)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvancesProfesionales', array($avancesProfesionales));

        return parent::setAvancesProfesionales($avancesProfesionales);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvancesProfesionalesLittle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvancesProfesionalesLittle', array());

        return parent::getAvancesProfesionalesLittle();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvancesProfesionalesLittle($avancesProfesionalesLittle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvancesProfesionalesLittle', array($avancesProfesionalesLittle));

        return parent::setAvancesProfesionalesLittle($avancesProfesionalesLittle);
    }

    /**
     * {@inheritDoc}
     */
    public function getExcepcionesPlazo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExcepcionesPlazo', array());

        return parent::getExcepcionesPlazo();
    }

    /**
     * {@inheritDoc}
     */
    public function getHito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHito', array());

        return parent::getHito();
    }

    /**
     * {@inheritDoc}
     */
    public function getAvanceHoras()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvanceHoras', array());

        return parent::getAvanceHoras();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvanceHoras($avanceHoras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvanceHoras', array($avanceHoras));

        return parent::setAvanceHoras($avanceHoras);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvance', array());

        return parent::getAvance();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvance($avance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvance', array($avance));

        return parent::setAvance($avance);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvancePRofesionales()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvancePRofesionales', array());

        return parent::getAvancePRofesionales();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvanceProfesionales($avanceProfesionales)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvanceProfesionales', array($avanceProfesionales));

        return parent::setAvanceProfesionales($avanceProfesionales);
    }

}
