<?php

namespace Proxies\__CG__\App\DataWarehouseBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DimProfesional extends \App\DataWarehouseBundle\Entity\DimProfesional implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'empresa', 'pnombre', 'snombre', 'papellido', 'sapellido', 'idProfesional', 'FtAvanceProyectoProfesional');
        }

        return array('__isInitialized__', 'empresa', 'pnombre', 'snombre', 'papellido', 'sapellido', 'idProfesional', 'FtAvanceProyectoProfesional');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DimProfesional $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setEmpresa($empresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresa', array($empresa));

        return parent::setEmpresa($empresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresa', array());

        return parent::getEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setPnombre($pnombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPnombre', array($pnombre));

        return parent::setPnombre($pnombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getPnombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPnombre', array());

        return parent::getPnombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setSnombre($snombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSnombre', array($snombre));

        return parent::setSnombre($snombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getSnombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSnombre', array());

        return parent::getSnombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPapellido($papellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPapellido', array($papellido));

        return parent::setPapellido($papellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getPapellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPapellido', array());

        return parent::getPapellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setSapellido($sapellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSapellido', array($sapellido));

        return parent::setSapellido($sapellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getSapellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSapellido', array());

        return parent::getSapellido();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProfesional()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdProfesional();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProfesional', array());

        return parent::getIdProfesional();
    }

    /**
     * {@inheritDoc}
     */
    public function setFtAvanceProyectoProfesional($FtAvanceProyectoProfesional)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFtAvanceProyectoProfesional', array($FtAvanceProyectoProfesional));

        return parent::setFtAvanceProyectoProfesional($FtAvanceProyectoProfesional);
    }

    /**
     * {@inheritDoc}
     */
    public function getFtAvanceProyectoProfesional()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFtAvanceProyectoProfesional', array());

        return parent::getFtAvanceProyectoProfesional();
    }

}
