<?php

namespace Proxies\__CG__\App\MediBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Licitacion extends \App\MediBundle\Entity\Licitacion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'nombre', 'fechaInicio', 'fechaTermino', 'cliente', 'dependencia', 'asignacion', 'estado', 'horasProgramadas', 'proyecto', 'excepcionesPlazo', 'estadoFinal', 'factTable', 'ultimoAvance', 'informacionAsignada', 'avance', 'finanzas', 'hito');
        }

        return array('__isInitialized__', 'id', 'nombre', 'fechaInicio', 'fechaTermino', 'cliente', 'dependencia', 'asignacion', 'estado', 'horasProgramadas', 'proyecto', 'excepcionesPlazo', 'estadoFinal', 'factTable', 'ultimoAvance', 'informacionAsignada', 'avance', 'finanzas', 'hito');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Licitacion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getProyecto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProyecto', array());

        return parent::getProyecto();
    }

    /**
     * {@inheritDoc}
     */
    public function getDependencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDependencia', array());

        return parent::getDependencia();
    }

    /**
     * {@inheritDoc}
     */
    public function getAsignacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsignacion', array());

        return parent::getAsignacion();
    }

    /**
     * {@inheritDoc}
     */
    public function removeDependencia($requerimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDependencia', array($requerimiento));

        return parent::removeDependencia($requerimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAsignacion($asignacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAsignacion', array($asignacion));

        return parent::removeAsignacion($asignacion);
    }

    /**
     * {@inheritDoc}
     */
    public function setDependencia($profesionales)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDependencia', array($profesionales));

        return parent::setDependencia($profesionales);
    }

    /**
     * {@inheritDoc}
     */
    public function setAsignacion($profesionales)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAsignacion', array($profesionales));

        return parent::setAsignacion($profesionales);
    }

    /**
     * {@inheritDoc}
     */
    public function setProyecto($proyectos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProyecto', array($proyectos));

        return parent::setProyecto($proyectos);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaInicio($fechaInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaInicio', array($fechaInicio));

        return parent::setFechaInicio($fechaInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaInicio', array());

        return parent::getFechaInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaTermino($fechaTermino)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaTermino', array($fechaTermino));

        return parent::setFechaTermino($fechaTermino);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaTermino()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaTermino', array());

        return parent::getFechaTermino();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliente($cliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliente', array($cliente));

        return parent::setCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente', array());

        return parent::getCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoFinal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoFinal', array());

        return parent::getEstadoFinal();
    }

    /**
     * {@inheritDoc}
     */
    public function getHorasProgramadas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorasProgramadas', array());

        return parent::getHorasProgramadas();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorasProgramadas($horasProgramadas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorasProgramadas', array($horasProgramadas));

        return parent::setHorasProgramadas($horasProgramadas);
    }

    /**
     * {@inheritDoc}
     */
    public function getFactTable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFactTable', array());

        return parent::getFactTable();
    }

    /**
     * {@inheritDoc}
     */
    public function setFactTable($arrayObjetos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFactTable', array($arrayObjetos));

        return parent::setFactTable($arrayObjetos);
    }

    /**
     * {@inheritDoc}
     */
    public function getExcepcionesPlazo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExcepcionesPlazo', array());

        return parent::getExcepcionesPlazo();
    }

    /**
     * {@inheritDoc}
     */
    public function getHito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHito', array());

        return parent::getHito();
    }

    /**
     * {@inheritDoc}
     */
    public function getAvanceTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvanceTotal', array());

        return parent::getAvanceTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvance($avance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvance', array($avance));

        return parent::setAvance($avance);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvance', array());

        return parent::getAvance();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinanzas($finanzas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinanzas', array($finanzas));

        return parent::setFinanzas($finanzas);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinanzas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinanzas', array());

        return parent::getFinanzas();
    }

}
