<?php

namespace Proxies\__CG__\App\MediBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User1 extends \App\MediBundle\Entity\User1 implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'username', 'fechaNacimiento', 'snombre', 'papellido', 'sapellido', 'pnombre', 'password', 'salt', 'correo', 'isActive', 'roles', 'empresa', 'direccion', 'comuna', 'telefono', 'imagen', 'imagenPerfil', 'misAvances', 'ultimoAvance', 'horasP', 'rango');
        }

        return array('__isInitialized__', 'id', 'username', 'fechaNacimiento', 'snombre', 'papellido', 'sapellido', 'pnombre', 'password', 'salt', 'correo', 'isActive', 'roles', 'empresa', 'direccion', 'comuna', 'telefono', 'imagen', 'imagenPerfil', 'misAvances', 'ultimoAvance', 'horasP', 'rango');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User1 $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaNacimiento($fechaNacimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaNacimiento', array($fechaNacimiento));

        return parent::setFechaNacimiento($fechaNacimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaNacimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaNacimiento', array());

        return parent::getFechaNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setPnombre($pnombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPnombre', array($pnombre));

        return parent::setPnombre($pnombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getPnombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPnombre', array());

        return parent::getPnombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setSnombre($snombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSnombre', array($snombre));

        return parent::setSnombre($snombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getSnombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSnombre', array());

        return parent::getSnombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPapellido($papellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPapellido', array($papellido));

        return parent::setPapellido($papellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getPapellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPapellido', array());

        return parent::getPapellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setSapellido($sapellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSapellido', array($sapellido));

        return parent::setSapellido($sapellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getSapellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSapellido', array());

        return parent::getSapellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreo', array());

        return parent::getCorreo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreo($correo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreo', array($correo));

        return parent::setCorreo($correo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', array());

        return parent::setSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', array($role));

        return parent::setRoles($role);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRole', array($role));

        return parent::removeRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function isEqualTo(\Symfony\Component\Security\Core\User\UserInterface $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEqualTo', array($user));

        return parent::isEqualTo($user);
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', array());

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', array($serialized));

        return parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresa($empresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresa', array($empresa));

        return parent::setEmpresa($empresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresa', array());

        return parent::getEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setRango($rango)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRango', array($rango));

        return parent::setRango($rango);
    }

    /**
     * {@inheritDoc}
     */
    public function getRango()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRango', array());

        return parent::getRango();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', array($direccion));

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', array());

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setComuna($comuna)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComuna', array($comuna));

        return parent::setComuna($comuna);
    }

    /**
     * {@inheritDoc}
     */
    public function getComuna()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComuna', array());

        return parent::getComuna();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', array($telefono));

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', array());

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function getImagen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagen', array());

        return parent::getImagen();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagen($imagen = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagen', array($imagen));

        return parent::setImagen($imagen);
    }

    /**
     * {@inheritDoc}
     */
    public function setPsNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPsNombre', array());

        return parent::setPsNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function getPsNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPsNombre', array());

        return parent::getPsNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagenPerfil($imagenPerfil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagenPerfil', array($imagenPerfil));

        return parent::setImagenPerfil($imagenPerfil);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagenPerfil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagenPerfil', array());

        return parent::getImagenPerfil();
    }

    /**
     * {@inheritDoc}
     */
    public function setMisAvances($misAvances)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMisAvances', array($misAvances));

        return parent::setMisAvances($misAvances);
    }

    /**
     * {@inheritDoc}
     */
    public function getMisAvances()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMisAvances', array());

        return parent::getMisAvances();
    }

    /**
     * {@inheritDoc}
     */
    public function setUltimoAvance($ultimoAvance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUltimoAvance', array($ultimoAvance));

        return parent::setUltimoAvance($ultimoAvance);
    }

    /**
     * {@inheritDoc}
     */
    public function getUltimoAvance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUltimoAvance', array());

        return parent::getUltimoAvance();
    }

    /**
     * {@inheritDoc}
     */
    public function getHorasP()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorasP', array());

        return parent::getHorasP();
    }

}
