<?php

namespace App\MediBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RequerimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequerimientoRepository extends EntityRepository
{
}
