<?php

namespace App\MediBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserLicitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLicitacionRepository extends EntityRepository
{
}
